### ISSUE TITLE
Create an NPC

### ISSUE THREAD

**Issue by Ember-Rane** [Ember-Rane/March-Lupus#8]
NPC human that can walk around.

**Comment by Ember-Rane** [comment]
NPCs have settings that can make them act differently. We need more normal villages, and more aggressive villagers.

**Comment by Ember-Rane** [comment]
Created base follow NPC logic in NPC branch

**Comment by DanilaFoxPro** [comment]
I think this issue/goal is fulfilled, I'll go ahead and add some more detailed NPC tasks and close this one.
